--- #YAML:1.0
name:                PITA-Test-Dummy-Perl5-Deps
version:             1.03
abstract:            CPAN Test Dummy for PITA Makefile.PL installs
license:             perl
author:              
    - Adam Kennedy <adamk@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    PITA::Test::Dummy::Perl5::Build: 1.01
    PITA::Test::Dummy::Perl5::Make: 1.02
    PITA::Test::Dummy::Perl5::MI:  0.64
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
